# Generated by Django 5.0.1 on 2024-02-21 04:00

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('image', models.ImageField(default='', upload_to='category/')),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Post',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('thumbnail', models.ImageField(default='', upload_to='Thumbnail/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Comment',
            fields=[
                ('c_no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.blog_comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blog_post')),
            ],
        ),
        migrations.CreateModel(
            name='Audio_Comment',
            fields=[
                ('c_no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.audio_comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blog_post')),
            ],
        ),
        migrations.CreateModel(
            name='Image_Comment',
            fields=[
                ('c_no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.image_comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blog_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload_Audio',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('audio_file', models.FileField(default='', upload_to='Audio/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload_Image',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('image_file', models.ImageField(default='', upload_to='Images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload_Video',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('video_file', models.FileField(default='', upload_to='video/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video_Comment',
            fields=[
                ('c_no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.video_comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blog_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
