# Generated by Django 5.0.1 on 2024-02-24 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.upload_audio'),
        ),
        migrations.AlterField(
            model_name='image_comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.upload_image'),
        ),
        migrations.AlterField(
            model_name='video_comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.upload_video'),
        ),
    ]
