# Generated by Django 5.0.1 on 2024-03-02 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_audio_comment_post_alter_image_comment_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_audio',
            name='user',
        ),
        migrations.DeleteModel(
            name='Audio_Comment',
        ),
        migrations.DeleteModel(
            name='Upload_Audio',
        ),
    ]
