# Generated by Django 5.0.1 on 2024-03-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_remove_upload_audio_user_delete_audio_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='content',
            field=models.TextField(),
        ),
    ]
